ChainSafe/game-docs-v2

docs/21_v2-integration.md, docs/8_erc20.md, docs/9_custom-interactions.md
custom token info added to erc20 and custom interactions
=> custom token info added

docs/21_v2-integration.md
=> docs update

docs/v2/6_erc20-interactions.md
Updated native token balance snippet
=> native token balance

dictionary.txt, docs/v2/10_webgl-browser.md, docs/v2/8_in-game-marketplace.md
* Formatting
* Capitalization
* Punctuation
* Messaging
Unresolved:
* Dead link in [Call Custom Contract](https://docs.gaming.chainsafe.io/current/webgl-browser#call-custom-contracts)
* @nftpixels to confirm if [Get User's Network](https://docs.gaming.chainsafe.io/current/webgl-browser#get-users-network) needs to be removed 
* "Back in 1.6.x you had to set this manually. But based on the script in 2.0.1, it's now being taken from the server settings when you setup your project"
Closes: [#126](https://github.com/ChainSafe/devrel/issues/126)
=> Touching up section 10 webGL browser build

docs/v2/10_webgl-browser.md, docs/v2/11_web3wallet-mobile-and-desktop.md, docs/v2/5_erc721-interactions.md
=> updating broken links

docs/v2/10_webgl-browser.md, docs/v2/11_web3wallet-mobile-and-desktop.md
Updated code to reflect real-world example of checking a transaction on WebGL & Web3Wallet
=> Update transaction check docs

docs/v2/2_installation.md
Streamlining/cutting out excess steps and screenshots, adding a direct download link, and reformatting a few sentences.
closes: [#141](https://github.com/ChainSafe/devrel/issues/141)
=> Cleaning up gaming docs "Installation" section

dictionary.txt
added 'changelogs'
closes: [#141](https://github.com/ChainSafe/devrel/issues/141)
=> dictionary

docs/v2/8_in-game-marketplace.md
=> collections video

docs/v2/10_webgl-browser.md, docs/v2/11_web3wallet-mobile-and-desktop.md
=> null check for tx

src/css/custom.css
Updating the highlighted font colours from original hex #FFEC3D to new hex #B4FF68 to be consistent with CSG branding.
=> Font colour update 

docs/1_chainsafe-gaming.md
=> Updating home page link

dictionary.txt, docs/v1/20_faq.md, docs/v1/3_installation.md, docs/v2/18_faq.md, docs/v2/3_installation.md
=> newtonsoft

dictionary.txt, docs/v2.5/10_voucher-minting-nfts.md, docs/v2.5/17_prefabs.md, sidebars.js
Added information for the mint 1155 prefab script that was just created in last PR.
=> Mint 1155 update

sidebars.js
=> Version update

docs/v2.5/17_faq.md
Amended minimal stripping from minimal to low in the faq section.
=> Amended minimal stripping in the faq

docs/v2.5/10_voucher-minting-nfts.md, docs/v2.5/11_interacting-with-smart-contracts.md, docs/v2.5/12_web2-like-authentication-using-web3auth.md, docs/v2.5/13_gasless-transactions-using-gelato.md, docs/v2.5/14_extending-the-sdk.md, docs/v2.5/15_ramp.md, docs/v2.5/16_lootboxes.md, docs/v2.5/17_block-racers-game.md, docs/v2.5/18_faq.md, docs/v2.5/1_cheat-sheet.md, docs/v2.5/2_getting-started.md, docs/v2.5/3_project-id-registration.md, docs/v2.5/4_setting-up-an-rpc-node.md, docs/v2.5/5_prefab-scripts.md, docs/v2.5/6_configuration.md, docs/v2.5/7_connecting-a-wallet.md, docs/v2.5/8_interacting-with-tokens.md, docs/v2.5/9_interacting-with-nfts.md, sidebars.js
=> CheatSheet Added

docs/v2.5/2_getting-started.md
=> Update getting started

docs/v2.5/5_prefab-scripts.md
Added Event data via tx receipt to prefab scripts
=> Event data via tx receipt

docs/v2.5/2_getting-started.md
Reverting the workaround for ramp as the sdk is now stable
=> Workaround revert

sidebars.js
Shifting sidebar placements so the docs are more prominent. Moved older versions to an archived menu.
Cleaned up sidebar js file to make it more readable.
=> Shifting sidebar placements

dictionary.txt, docs/v2.6/8_login-process.md
An edit of 2.6 docs. Mostly code samples purification.
=> 2.6 Docs edit

docs/v2.6/7_setting-up-an-rpc-node.md
Setting up an RPC node is technically optional, drawing attention to that.
=> Fixing rpc info

docs/v2.6/16_block-racers-game.md, docs/v2.6/9_sample-scripts-and-chain-interactions.md
Currently the scripts fail because Monobehaviour needs using UnityEngine to run. I updated all the scripts to include the line.
=> Added Using UnityEngine to scripts

docs/v2.6/1_getting-started.md, docs/v2.6/8_login-process.md, docs/v2.6/9_sample-scripts-and-chain-interactions.md
Updated broken links on pages, 1155 mint sample scrip, and PlayerAddress function in login process.
=> 2.6 rework

docs/marketplace-api/spec/paths/get_project_items.yaml, docs/marketplace-api/spec/paths/get_project_marketplace_items.yaml
=> feat: marketplace token filters

docs/v2.6/1_getting-started.md, docs/v2.6/9_sample-scripts-and-chain-interactions.md
Also added the docs section for people who want to use SDK with the private key directly.
=> Added the section for people to choose their wallet in the Getting Started

dictionary.txt, docs/v2.6/19_abi-to-csharp-converter.md, docs/v2.6/8_login-process.md, docs/v2.6/9_sample-scripts-and-chain-interactions.md
Added web3initialized event to the docs
=> V3 updates

dictionary.txt, docs/v2.6/18_faq.md
Explaining how devs themselves can use our SDK with their custom webGL template and with react-unity-webgl
=> Explaining how devs themselves can use our SDK with their custom webGL template and with react-unity-webgl

dictionary.txt, docs/1_chainsafe-gaming.md, docs/nft_launchpad/1_introduction.md, docs/nft_launchpad/2_details.md, docs/nft_launchpad/3_tutorial.md, docs/nft_marketplace/1_introduction.md, docs/nft_marketplace/2_tutorial.md, docs/v2.6/10_voucher-minting-nfts.md, docs/v2.6/11_gasless-transactions-using-gelato.md, docs/v2.6/12_ramp.md, docs/v2.6/13_lootboxes.md, docs/v2.6/14_extending-the-sdk.md, docs/v2.6/16_block-racers-game.md, docs/v2.6/17_block-blasterz-game.md, docs/v2.6/18_faq.md, docs/v2.6/20_mud.md, docs/v2.6/3_metamask.md, docs/v2.6/4_reown.md, docs/v2.6/5_web3auth.md, docs/v2.6/6_hyperplay.md, docs/v2.6/7_setting-up-an-rpc-node.md, docs/v2.6/9_sample-scripts-and-chain-interactions.md
Updated all links with utm tags
=> Updated all links with utm tags
